name: Trigger auto deployment for mvcecommerce
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mvcecommerce-AutoDeployTrigger-5c0b06fd-d832-4f15-84f9-d4f3009bb5fc.yml'
  # Allow manual trigger 
  workflow_dispatch:      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.MVCECOMMERCE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.MVCECOMMERCE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.MVCECOMMERCE_AZURE_SUBSCRIPTION_ID }}
          
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          containerAppName: mvcecommerce
          resourceGroup: newgrp
          imageToDeploy: mvcecommerce.azurecr.io/gh-action/container-app:${{ github.sha }}
